version: '2'

services:
  keycloak:
    image: jboss/keycloak
    ports:
      - "8083:8080"
    environment:
      - "KEYCLOAK_USER=admin"
      - "KEYCLOAK_PASSWORD=admin"
      - "KEYCLOAK_WELCOME_THEME=civadis"
    volumes:
      - ./civadis/:/opt/jboss/keycloak/themes/civadis/
